// <auto-generated />
using System;
using Api.Repository.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tech"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Animals"
                        },
                        new
                        {
                            Id = 3,
                            Name = "World"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Politics"
                        });
                });

            modelBuilder.Entity("Api.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PostId = 1,
                            Text = "Gozel Post1",
                            Time = new DateTime(2008, 3, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            PostId = 1,
                            Text = "Gozel Post1",
                            Time = new DateTime(2008, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            PostId = 2,
                            Text = "Gozel Post2",
                            Time = new DateTime(2008, 3, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            PostId = 2,
                            Text = "Gozel Post2",
                            Time = new DateTime(2008, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            PostId = 2,
                            Text = "Gozel Post2",
                            Time = new DateTime(2008, 3, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 6,
                            PostId = 3,
                            Text = "Gozel Post3",
                            Time = new DateTime(2008, 3, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 7,
                            PostId = 4,
                            Text = "Gozel Post4",
                            Time = new DateTime(2008, 3, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 8,
                            PostId = 4,
                            Text = "Gozel Post4",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 9,
                            PostId = 5,
                            Text = "Gozel Post5",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 10,
                            PostId = 5,
                            Text = "Gozel Post5",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 11,
                            PostId = 5,
                            Text = "Gozel Post5",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 12,
                            PostId = 5,
                            Text = "Gozel Post5",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 13,
                            PostId = 5,
                            Text = "Gozel Post5",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 14,
                            PostId = 5,
                            Text = "Gozel Post5",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 15,
                            PostId = 5,
                            Text = "Gozel Post5",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 16,
                            PostId = 5,
                            Text = "Gozel Post5",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 17,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 18,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 19,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 20,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 21,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 22,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 23,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 24,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 25,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 26,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 27,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 28,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 29,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 30,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 31,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 32,
                            PostId = 6,
                            Text = "Gozel Post6",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Api.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Admin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Show")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "Post1",
                            Show = 8,
                            Text = "Post1 Cateogry1 Text asdasdasdasd",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Content = "Post2",
                            Show = 8,
                            Text = "Post2 Category1 Text dfgfdgfgfgfdgfd",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Content = "Post3",
                            Show = 34,
                            Text = "Post3 Category1 Text dfgdfgfdgfdgdf",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Content = "Post4",
                            Show = 5,
                            Text = "Post4 Category2 Text l,glmtomgormf",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Content = "Post5",
                            Show = 234,
                            Text = "Post5 Category2 Text msdfmsl;dfm",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Content = "Post6",
                            Show = 45,
                            Text = "Post6 Category3 Text pppp,asd, aas,s",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Content = "Post7",
                            Show = 11,
                            Text = "Post7 Category3 Text sadfgkusdstujhhtjh",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Content = "Post8",
                            Show = 34,
                            Text = "Post8 Category3 Text jhgmxdnsbdjurt jtg jgf",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Content = "Post9",
                            Show = 55,
                            Text = "Post9 Category3 Text scrw356v5e7v6ruvuv",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Content = "Post10",
                            Show = 67,
                            Text = "Post10 Category3 Textk9mkuj262626fhfh hfdh",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Content = "Post11",
                            Show = 1,
                            Text = "Post11 Category4 Text wweqqwweqqqwe",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Content = "Post12",
                            Show = 90,
                            Text = "Post12 Category4 Text aaaaaagggggggrrrrrrreeeeeeeeeg 343434",
                            Time = new DateTime(2008, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Api.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Jean@gmail.com",
                            Name = "Jean",
                            Password = "Jean123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Anna@gmail.com",
                            Name = "Anna",
                            Password = "Anna123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Jon@gmail.com",
                            Name = "Jon",
                            Password = "Jon123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Alison@gmail.com",
                            Name = "Alison",
                            Password = "Alison123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Mike@gmail.com",
                            Name = "Mike",
                            Password = "Mike123"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Jony@gmail.com",
                            Name = "Jony",
                            Password = "Jony123"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Anastasiya@gmail.com",
                            Name = "Anastasiya",
                            Password = "Anastasiya123"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Coni@gmail.com",
                            Name = "Coni",
                            Password = "Coni123"
                        });
                });

            modelBuilder.Entity("Api.Models.Post", b =>
                {
                    b.HasOne("Api.Models.Category", null)
                        .WithMany("PostList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
